### ISSUE TITLE
Debug setup-repository command

### ISSUE THREAD

**Issue by artgoldberg** [KarrLab/karr_lab_build_utils#10]
Did not work as advertised. I ran
    karr_lab_build_utils setup-repository wc_env --description 'Portable environment for easily installing and running WC code' --public

Local files were created, but neither local nor github repos were made. Done inside a Docker container.

**Comment by artgoldberg** [comment]
I completed repo setup by following https://help.github.com/articles/adding-an-existing-project-to-github-using-the-command-line/#platform-linux

**Comment by jonrkarr** [comment]
Please provide the exact steps that you used, particularly how the
environment (GitHub API credentials, GitHub SSH credentials, etc.) was
setup.

**Comment by artgoldberg** [comment]
These are some .ssh files:
docker [.ssh]$ ls -al
total 20
drwxr-xr-x 1 root root    4096 Apr  4 13:14 .
drwx------ 1 root root    4096 Apr  4 14:01 ..
-rw------- 1  502 dialout 3243 Mar 26 15:22 id_rsa
-rw-r--r-- 1  502 dialout  747 Mar 26 15:22 id_rsa.pub
-rw-r--r-- 1 root root    1668 Apr  4 13:26 known_hosts
docker [.ssh]$ m known_hosts 
github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDB
fOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mb
UoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604y
dGXA8VJiS5ap43JXiUFFAaQ==
github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDB
fOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mb
UoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604y
dGXA8VJiS5ap43JXiUFFAaQ==
|1|t6aawoBjTJv7VZnA3YXmcwLA+W0=|QwhrVaxd6UjM2MmYY37TKEYRbXQ= ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6
TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfD
ESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JE
AvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
|1|0xQeQOQVfsQznXlyI1SlcP6Ia9w=|WO23tdU/gzQNmDQpKrOzJTT7Id8= ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6
TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfD
ESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JE
AvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==

This is .gitconfig:
docker [~]$ more .gitconfig 
[url "ssh://git@github.com/"]
    insteadOf = https://github.com/
[user]
	email = artgoldberg@gmail.com
	name = Arthur Goldberg
[push]
	default = simple

These files were created: 
docker [wc_env]$ find . | grep -E -v "\.git"
.
./LICENSE
./requirements.txt
./tests
./tests/requirements.txt
./tests/test_core.py
./tests/test_main.py
./MANIFEST.in
./docs
./docs/index.rst
./docs/requirements.txt
./docs/references.bib
./docs/conf.py
./docs/overview.rst
./docs/spelling_wordlist.txt
./docs/installation.rst
./docs/references.rst
./docs/about.rst
./.karr_lab_build_utils.yml
./README.md
./setup.py
./setup.cfg
./wc_env
./wc_env/__init__.py
./wc_env/core.py
./wc_env/VERSION
./wc_env/__main__.py
./.circleci
./.circleci/config.yml
./requirements.optional.txt

I've gotta run, but can provide more later.

**Comment by jonrkarr** [comment]
I see where the documentation was confusing. There's three methods/command line programs:

- create_package interactive program
    - Creates a new GitHub repo and clones repo locally (**create_repository**)
    - Setups file structure and default files for local copy of Git repo (**setup_repository**)
    - Links GitHub repo to CircleCI, Coveralls, Code Climate, Read the Docs
    - Adds package to our code dashboard (https://code.karrlab.org)
    - Updates downstream dependencies in .karr_lab_build_utils.yml
    - Adds badges to README.md
- create_repository
    - Creates a new GitHub repo and clones repo locally
    - Called by create_package
- setup_repository
    - Setups file structure and default files for local copy of Git repo
    - Called by create_package

The first method is interactive. It prompts you for all of the needed information. It also provides instructions for the steps that can't be automated (because some of our third party services don't provide complete APIs).

I clarified the docstrings, the help for the command line program, and the documentation. See
https://docs.karrlab.org/karr_lab_build_utils/latest/tutorial_admins.html#creating-a-new-package
