### ISSUE TITLE
Problem with uploading documentation to docs.karrlab.org

### ISSUE THREAD

**Issue by artgoldberg** [KarrLab/karr_lab_build_utils#30]
In the documentation for [wc_env_manager](https://docs.karrlab.org/wc_env_manager/master/0.0.1/installation.html) the link for [An Introduction to Whole-Cell Modeling](https://docs.karrlab.org/intro_to_wc_modeling/latest/installation.html) is dead. This occurs because the 'latest/installation.html' page doesn't exist.

**Comment by jonrkarr** [comment]
Fixed
