### ISSUE TITLE
Circle CI

### ISSUE THREAD

**Issue by bilalshaikh42** [KarrLab/karr_lab_build_utils#31]
Script does not correctly prompt for circle CI setup. After clicking on project settings, no action is taken. Build on circle CI fails as repo has not been pushed with circle config. 

Visit "https://circleci.com/add-projects/gh/KarrLab"
Continue? [Y/n]: 
Search for the "datanator_rest_api" repository and click its "Set Up Project" button
Continue? [Y/n]: 
Click the "Start building" button
Continue? [Y/n]: 
Click the "Project settings" icon
Continue? [Y/n]:

**Comment by jonrkarr** [comment]
Fixed
