### ISSUE TITLE
Support python semantic release in version file

### ISSUE THREAD

**Issue by bilalshaikh42** [KarrLab/karr_lab_build_utils#39]
[Python Semantic Release](https://github.com/relekang/python-semantic-release) is a package that automates versioning and releasing of python packages. It relies on the version information to be stored in a variable within a file. This is incompatible with the current system which uses the `VERSION` file that contains the version in plain text. 

A proposed way to support the package while maintaining current functionality is illustrated here: https://stackoverflow.com/a/7071358.

Using the ` _version.py `file would add support for semantic release. 
The `_version.py` file could be read by setup.py  exactly as the current VERSION file is. This would also provide the  `__ version __ `property on all modules created, which the current implementation does not.
 
The pkg_utils repo would need to be updated with https://github.com/KarrLab/pkg_utils/pull/1 to prevent exceptions if the VERSION file is removed. 

@jonrkarr If you agree with this, I can make a pull request to implement these changes.

**Comment by bilalshaikh42** [comment]
https://github.com/KarrLab/pkg_utils/pull/1 has been updated to accept either a VERSION file or a _version.py file

**Comment by jonrkarr** [comment]
Done
